# ===== Gradle =====
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
# File system watching
org.gradle.vfs.watch=true

# Mémoire du daemon Gradle
org.gradle.jvmargs=-Xmx8g -XX:+UseParallelGC -Dfile.encoding=UTF-8

# ===== Kotlin =====
kotlin.incremental=true
kotlin.daemon.jvm.options=-Xmx4g

# ===== Kotlin/Native =====
kotlin.native.enableParallelGC=true
kotlin.native.cacheKind=static
kotlin.native.cacheKind.iosArm64=static
kotlin.native.cacheKind.iosSimulatorArm64=static

# ===== Android / Compose =====
android.useAndroidX=true
android.nonTransitiveRClass=true
compose.multiplatform.enable.lazy.resource.loading=true

# ===== KMP =====
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true

# ===== Divers =====
xcodeproj=~/ios
