[versions]
activityCompose = "1.9.1"
appcompat = "1.7.0"
arrow = "1.2.1"
assertk = "0.28.0"
coil = "2.6.0"
composeLintChecks = "1.3.1"
coreKtx = "1.13.1"
coreKtxVersion = "1.6.1"
coreTesting = "2.2.0"
credentials = "1.2.2"
datastore = "1.1.1"
facebookAndroidSdk = "16.3.0"
firebaseBom = "33.2.0"
firebaseKtx = "23.0.0"
firebaseUiAuth = "7.2.0"
googleIdentity = "1.1.1"
googleServices = "4.4.2"
gradle = "8.7.0"
gson = "2.11.0"
javapoet = "1.13.0"
junitJupiter = "5.10.2"
junitKtx = "1.2.1"
koin = "3.5.6"
kotlinGradlePlugin = "2.0.20"
kotlinxCollectionsImmutable = "0.3.7"
kotlinxCoroutinesTest = "1.8.0"
kotlinxSerialization = "1.6.3"
ksp = "2.0.20-1.0.24"
lifecycleViewmodelCompose = "2.7.0"
loggingInterceptor = "4.12.0"
material = "1.6.8"
material3 = "1.2.1"
media3 = "1.4.1"
mockk = "1.13.9"
mockkAndroid = "1.13.9"
navigationTesting = "2.7.7"
navigationUiKtx = "2.8.0-rc01"
okhttp = "4.12.0"
paging = "3.3.2"
playServicesAuth = "21.2.0"
retrofit = "2.9.0"
room = "2.6.1"
runtime = "1.6.8"
truth = "1.4.1"
turbine = "0.12.1"
uiTooling = "1.6.8"
youtube = "12.1.0"
jetbrainsKotlinJvm = "1.9.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeLintChecks" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationUiKtx" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookAndroidSdk" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookAndroidSdk" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseKtx" }
firebase-firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
google-identity = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleIdentity" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelCompose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "androidx.compose.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "material" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtxVersion" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
youtube-player = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "youtube" }

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinGradlePlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinGradlePlugin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
