[versions]
activityCompose = "1.8.2"
appcompat = "1.6.1"
arrow = "1.2.1"
assertk = "0.28.0"
coil = "2.6.0"
composeLintChecks = "1.3.1"
coreKtx = "1.12.0"
coreKtxVersion = "1.5.0"
coreSplashscreen = "1.0.1"
coreTesting = "2.2.0"
facebookAndroidSdk = "16.3.0"
firebaseBom = "32.8.0"
firebaseKtx = "22.3.1"
firebaseUiAuth = "7.2.0"
googleServices = "4.4.1"
gradle = "8.4.0"
hiltAndroid = "2.50"
hiltAndroidGradlePlugin = "2.50"
hiltAndroidTesting = "2.50"
hiltCompiler = "2.50"
hiltNavigationCompose = "1.2.0"
javapoet = "1.13.0"
junitJupiter = "5.10.2"
junitKtx = "1.1.5"
kotlinGradlePlugin = "1.9.22"
kotlinxCollectionsImmutable = "0.3.7"
kotlinxCoroutinesTest = "1.8.0"
lifecycleViewmodelCompose = "2.7.0"
loggingInterceptor = "4.12.0"
material = "1.6.5"
material3 = "1.2.1"
mockk = "1.13.9"
mockkAndroid = "1.13.9"
navigationTesting = "2.7.7"
navigationUiKtx = "2.7.7"
okhttp = "4.12.0"
paging = "3.2.1"
playServicesAuth = "21.0.0"
retrofit = "2.9.0"
room = "2.6.1"
runtime = "1.6.5"
truth = "1.4.1"
uiTooling = "1.6.5"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow"}
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeLintChecks" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationUiKtx" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookAndroidSdk" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookAndroidSdk" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseKtx" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompiler" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelCompose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "androidx.compose.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtxVersion" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }

[plugins]
