object Modules {
    const val AUTHENTICATION_DATA = ":core:authentication:data"
    const val AUTHENTICATION_DOMAIN = ":core:authentication:domain"
    const val COMMON = ":core:common"
    const val DAO = ":core:database:dao"
    const val DATABASE = ":core:database"
    const val DESIGN = ":core:design"
    const val DI = ":core:di"
    const val LOGIN_DOMAIN = ":core:login:domain"
    const val LOGIN_PRESENTATION = ":core:login:presentation"
    const val MOVIE_DATA = ":feature:movies:data"
    const val MOVIE_DOMAIN = ":feature:movies:domain"
    const val MOVIE_PRESENTATION = ":feature:movies:presentation"
    const val NAVIGATION = ":core:navigation"
    const val NETWORK = ":core:network"
    const val SESSION_DOMAIN = ":core:session:domain"
    const val SPLASHSCREEN_PRESENTATION = ":core:splashscreen:presentation"
}
