name: Run Unit Tests

on:
    pull_request:
        branches: [ "main", "develop" ]
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup environment (cache, JDK, SDK)
                uses: actions/cache@v4
                with:
                    path: |
                        ~/.gradle/caches/build-cache
                        ~/.gradle/wrapper/
                    key: >
                        ${{ runner.os }}-gradle-
                        ${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-
                        ${{ runner.os }}-

            -   name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'zulu'
                    cache: gradle

            -   name: Setup Android SDK
                uses: android-actions/setup-android@v3
                with:
                    cache: android

            -   name: Set facebook.properties
                run: echo "${{ secrets.FACEBOOK_CLIENT_TOKEN }}" | base64 -d > facebook.properties

            -   name: Set google-services.json
                run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

            -   name: Create Facebook file
                run: cat /home/runner/work/hobby-matchmaker/hobby-matchmaker/facebook.properties | base64

            #-   name: Fill facebook file
            #    env:
            #        DATA: ${{ secrets.FACEBOOK_CLIENT_TOKEN }}
            #    run: echo "facebook_client_token=$DATA" > /home/runner/work/hobby-matchmaker/hobby-matchmaker/facebook.properties

            #-   name: Create google-services file
            #    run: cat /home/runner/work/hobby-matchmaker/hobby-matchmaker/app/google-services.json | base64

            #-   name: Fill google-services file
            #    env:
            #        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
            #    run: echo $DATA > /home/runner/work/hobby-matchmaker/hobby-matchmaker/app/google-services.json

            -   name: Grant execute permission for gradlew
                run: chmod +x ./gradlew

    tests:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            -   uses: actions/checkout@v4
            -   name: Run Unit tests
                run: ./gradlew :app:testDebugUnitTest :testsUtils:core:testDebugUnitTest :testUtils:feature:testDebugUnitTest
